  parquet_path: "W:/VSCode/drone_project/datasets/labeled_data" #note: yaml likes forward slashes

  test_size: 0.2
  random_seed: 42
  input_dim: 13
  output_dim: 4

  batch_size: 32
  learning_rate: 0.001
  num_epochs: 1000
  patience: 20
  save: true