  parquet_path: "W:/VSCode/drone_project/datasets/labeled_data" #note: yaml likes forward slashes /demo3.parquet
  scaler_path: "W:/VSCode/drone_project/scaler/scaler.bin"
  test_size: 0.01
  random_seed: 42
  input_dim: 13
  output_dim: 4

  batch_size: 64
  learning_rate: 0.0001
  num_epochs: 337
  patience: 20
  l1: 0.001
  l2: 0.001
  save: true